Create race endpoint
Elieroz/blisart-api pull request #4
Opened 2023-03-26 12:29 UTC by Elieroz

Para poder crear races, en plan, ¿sabes?

2023-03-26 12:30 UTC, Elieroz commented
Se han seguido los consejos de @darklechan para implementar una arquitectura DDD. ;) No hay tests.

2023-03-26 12:30 UTC, darklechan commented
no hay tests

2023-03-26 12:31 UTC, darklechan requested changes
faltan test unitarios

2023-03-26 12:31 UTC, Elieroz commented
Ya tienes deberes.

2023-03-26 12:32 UTC, Elieroz commented
> faltan test unitarios

Ya tienes deberes.

2023-06-13 16:47 UTC, darklechan approved these changes

2023-06-13 16:47 UTC, merged